import logging
from fastapi import APIRouter, Depends, status, HTTPException
from typing import Dict, Any

from app.middleware.auth_middleware import get_current_user
from app.database import get_collection
from app.graph import app_graph
from app.state import VerdictState

router = APIRouter(tags=["LangGraph Multi-Agent Audit Pipeline"])
logger = logging.getLogger(__name__)

@router.post("/workspace/{workspace_id}/run-analysis", status_code=status.HTTP_200_OK)
async def run_analysis(workspace_id: str, current_user: dict = Depends(get_current_user)):
    """
    POST /workspace/{workspace_id}/run-analysis
    Executes the VerdictIQ multi-agent legal intelligence analysis pipeline from end to end using LangGraph.
    Stores results persistently in MongoDB Atlas.
    """
    logger.info(f"FastAPI: Triggered run-analysis for workspace: {workspace_id} (User: {current_user.get('email')})")

    # Initialize the VerdictState for the LangGraph workflow
    initial_state: VerdictState = {
        "workspace_id": workspace_id,
        "lawyer_side": None,
        "case_context": None,
        "agent0_output": None,
        "agent1_output": None,
        "agent2_output": None,
        "agent3_output": None,
        "current_stage": "started"
    }

    # Execute the workflow
    try:
        final_state = await app_graph.ainvoke(initial_state)
    except Exception as e:
        logger.error(f"LangGraph Workflow failed for workspace {workspace_id}: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Multi-agent workflow execution failed: {e}"
        )

    logger.info(f"LangGraph Workflow completed successfully for workspace {workspace_id}")

    return {
        "success": True,
        "message": "VerdictIQ multi-agent analysis completed successfully using LangGraph + LangChain workflow.",
        "workspace_id": workspace_id,
        "stages_completed": [
            "load_workspace_node", 
            "agent0_node", 
            "agent1_node", 
            "agent2_node", 
            "agent3_node", 
            "save_results_node"
        ],
        "results": {
            "agent0_output": final_state.get("agent0_output"),
            "agent1_output": final_state.get("agent1_output"),
            "agent2_output": final_state.get("agent2_output"),
            "agent3_output": final_state.get("agent3_output")
        }
    }

@router.get("/workspace/{workspace_id}/report", status_code=status.HTTP_200_OK)
async def get_report(workspace_id: str, current_user: dict = Depends(get_current_user)):
    """
    GET /workspace/{workspace_id}/report
    Fetches the persistent consolidated legal intelligence report generated by Agent 3 from MongoDB.
    """
    logger.info(f"FastAPI: Fetching report for workspace: {workspace_id}")

    # Fetch stored report from database
    agent3_collection = get_collection("agent3_final_reports")
    doc = await agent3_collection.find_one({"workspace_id": workspace_id})
    
    if not doc:
        raise HTTPException(
            status_code=404,
            detail="Agent 3 report not found. Execute run-analysis first."
        )

    # Return the structured results matching the expected Output Format schema
    return {
        "workspace_id": workspace_id,
        "executive_summary": doc.get("executive_summary", ""),
        "case_strength": doc.get("case_strength", "Moderate Case"),
        "strongest_evidence": doc.get("strongest_evidence", []),
        "weak_evidence": doc.get("weak_evidence", []),
        "missing_evidence": doc.get("missing_evidence", []),
        "identified_loopholes": doc.get("loopholes", []),
        "counterargument_risks": doc.get("courtroom_risks", []),
        "legal_references": doc.get("legal_references", []),
        "strategic_recommendations": doc.get("strategic_recommendations", []),
        "overall_case_assessment": doc.get("final_case_assessment", ""),
        "ai_disclaimer": "This AI-generated analysis is intended for legal research assistance and strategic support only. It should not be treated as definitive legal advice.",
        "report_ready": True
    }
